import os
os.environ["PYGAME_HIDE_SUPPORT_PROMPT"] = "hide"
import pygame as pg


SCREEN_WIDTH = 864
SCREEN_HEIGHT = 936
SIZE = [SCREEN_WIDTH, SCREEN_HEIGHT]
SCROLL_SPEED = 4
GROUND_HEIGHT = 768
FRAMERATE = 60
SCROLL_THRESHOLD = 35
PIPE_LENGTH = [-180, 180]
PIPE_INTERVAL = [1500, 100000]
GAP_INTERVAL = [160, 200]
screen = pg.display.set_mode(SIZE)
